version: 2.1

orbs:
 jira: circleci/jira@1.3.1
jobs:
  hello-job:
    docker:
      - image: cimg/python:3.10.7
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - jira/notify:
          environment_type: staging
          environment: Staging
          job_type: deployment

workflows:
  my-workflow:
    jobs:
      - hello-job

