version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/python:3.10.7
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world ${API_TOKEN}" # run the `echo` command
      - run: python --version
      - run: curl https://www.google.com
      - run: curl --request POST --url 'https://prasanna-test.atlassian.net/rest/api/3/issue/SAM-2/transitions' --user 'prasannaramesh2000@gmail.com:UR7LCxyMWCFGIbaqstDtFF5B' --header 'Accept'.' application/json' --header 'Content-Type':' application/json' --data '{"transition"':' {"id"':' "31"}}'
      - run: echo "export COMMIT_MESSAGE=\"$(git log --format=oneline -n 1 $CIRCLE_SHA1)\"">> ~/.bashrc
      - run: echo "$COMMIT_MESSAGE"



workflows:
  my-workflow:
    jobs:
      - hello-job

