version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/python:3.10.7
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: python --version
      - run: curl https://www.google.com
      - run: curl --request POST \
  --url 'https://prasanna-test.atlassian.net/rest/api/3/issue/SAM-1/transitions' \
  --user 'prasannaramesh2000@gmail.com:RHJZxYsxBDtgSinubKL8404D' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data '{
  "transition": {
    "id": "31"
  }}'

      

workflows:
  my-workflow:
    jobs:
      - hello-job

